version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - app-network
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - app-network
  mongo:
    image: mongo:7.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
  redis:
    image: redis/redis-stack:latest
    container_name: tmsRedis
    ports:
      - "6389:6379"
      - "8001:8001"
    volumes:
      - ~/data/redis/data:/data

  mysql:
    image: mysql:8
    container_name: mysql8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: tmsroot  # Change this to a strong password
      MYSQL_DATABASE: mysql_tms_ti               # Optional: default database
      MYSQL_USER: tmsuser                 # Optional: non-root user
      MYSQL_PASSWORD: tmsuser         # Optional: non-root user's password
    ports:
      - "3306:3306"
    volumes:
      - ~/data/mysql:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - app-network
  setup:
    image: bikashhasmobile/setup-script:1.0
    depends_on:
      - kafka
      - mongo
    restart: "no"
  realtime-transaction-tracker:
    image: bikashhasmobile/realtime-transaction-tracker:9.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    depends_on:
      - kafka
      - mongo
      - setup
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-db:27017/mybank
      - SPRING_R2DBC_URL=r2dbc:mysql://mysql8:3306/mysql_tms_ti  # Connect to MySQL container
      - SPRING_R2DBC_USERNAME=tmsuser
      - SPRING_R2DBC_PASSWORD=tmsuser
    networks:
      - app-network
  view-transaction-service:
    image: bikashhasmobile/view_transaction:9.0.3
    container_name: view_transaction_service
    ports:
      - "8081:8082"
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
    - SPRING_R2DBC_URL=r2dbc:mysql://mysql8:3306/mysql_tms_ti  # Connect to MySQL container
    - SPRING_R2DBC_USERNAME=tmsuser
    - SPRING_R2DBC_PASSWORD=tmsuser
    - CORSURL=$${cors.url:localhost:8081}
    - KAFKA_BOOTSTRAP_ADDRESS=kafka:9092
    networks:
      - app-network

volumes:
  kafka-data:
  mongo-data:
  mysql-data:
networks:
  app-network:
    driver: bridge